version: '3.3'

volumes:
  pg_data_foodgram:
  static_foodgram:
  media_foodgram:

services:

  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data_foodgram:/var/lib/postgresql/data

  backend:
    build: ../backend/foodgram
    env_file: .env
    depends_on:
      - db
    volumes:
      - static_foodgram:/app/static/
      - media_foodgram:/app/media/

  frontend:
    env_file: .env
    build: ../frontend
    volumes:
      - ./frontend/:/app/result_build/

  gateway:
    container_name: gateway
    image: nginx:1.23.3-alpine
    restart: always
    depends_on:
      - db
      - backend
      - frontend
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_foodgram:/etc/nginx/html/static/
      - media_foodgram:/etc/nginx/html/media/
