version: '3.3'

volumes:
  pg_data_foodgram:
  static_foodgram:
  media_foodgram:
  static:

services:

  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data_foodgram:/var/lib/postgresql/data

  backend:
    image: ivan0py/foodgram_backend
    env_file: .env
    volumes:
      - static_foodgram:/app/static
      - media_foodgram:/app/media
    depends_on:
      - db

  frontend:
    image: ivan0py/foodgram_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/app/result_build/build

  gateway:
    container_name: gateway
    image: ivan0py/foodgram_gateway
    env_file: .env
    restart: always
    ports:
      - '8000:80'
    depends_on:
      - db
      - backend
      - frontend
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_foodgram:/etc/nginx/html/static/
      - media_foodgram:/etc/nginx/html/media/
